name: Test Casks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Homebrew
        run: |
          brew --version

      - name: Audit Casks
        run: |
          brew audit --cask --strict Casks/*.rb

      - name: Check Cask style
        run: |
          brew style --fix Casks/*.rb

      - name: Validate Casks
        run: |
          for cask in Casks/*.rb; do
            name="$(basename "$cask" .rb)"
            brew info --cask "./$cask"
          done